apiVersion: apps/v1
kind: Deployment
metadata:
  name: fivefilters
  namespace: go-reader
  labels:
    app: fivefilters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fivefilters
  template:
    metadata:
      labels:
        app: fivefilters
    spec:
      containers:
        - name: fivefilters
          image: heussd/fivefilters-full-text-rss:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: APACHE_RUN_USER
              value: "www-data"
            - name: APACHE_RUN_GROUP
              value: "www-data"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: fivefilters
  namespace: go-reader
  labels:
    app: fivefilters
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: fivefilters

