services:
  go-reader:
    build: .
    ports:
      - "8080:8080"
  fullfeedrss:
      image: 'heussd/fivefilters-full-text-rss:latest'
      environment:
          # Leave empty to disable admin section
          - FTR_ADMIN_PASSWORD=
      volumes:
          - 'rss-cache:/var/www/html/cache/rss'
      ports:
          - '8081:80'
volumes:
    rss-cache:
