services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE=http://localhost:8080/api
    depends_on:
      - go-reader
  go-reader:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
  fullfeedrss:
    image: "heussd/fivefilters-full-text-rss:latest"
    environment:
      # Leave empty to disable admin section
      - FTR_ADMIN_PASSWORD=
    volumes:
      - "rss-cache:/var/www/html/cache/rss"
    ports:
      - "8081:80"
  postgres:
    image: postgres:17.5-alpine3.22
    restart: always
    #https://hub.docker.com/_/postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rss-cache:
  postgres_data:
