apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: tilt
servers: 1
agents: 0

ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer

registries:
  create:
    name: tilt

options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
